# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write  

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt

    - name: Run
      run: |
        python main.py

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1.0.4
      with:
        path: data/

    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.2
